server:
  address: 0.0.0.0
  port: 9102
  servlet:
    context-path: /SignServer

spring:
  jta:
    enabled: true
  datasource:
    charge:
      unique-resource-name: chargeDataSource
      xa-data-source-class-name: com.microsoft.sqlserver.jdbc.SQLServerXADataSource
      xa-properties:
        URL: jdbc:sqlserver://localhost:1433;DatabaseName=Charges_jdjs
        user: sa
        password: Charge123
      maxActive: 100
      initialSize: 10
      maxWait: 60000
      minIdle: 10
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: true
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
    sign:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/sign?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowMultiQueries=true
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: aa572757748
      maxActive: 100
      initialSize: 10
      maxWait: 60000
      minIdle: 10
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: true
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
    log:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/sign_log?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowMultiQueries=true
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: aa572757748
      maxActive: 100
      initialSize: 10
      maxWait: 60000
      minIdle: 10
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: true
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

domain: http://baoming.gxgj.com

wkhtmlurl: d:\Program Files\wkhtmltopdf\bin\wkhtmltoimage.exe

noticeFileUrl: D:\upload\notice\

importStudentUrl: D:\upload\import

signDataSourceBackUp: cmd /c ${mysqlBin}mysqldump -u${spring.datasource.sign.username} -p${spring.datasource.sign.password} sign >${signDataSourceBackUpUrl}

mysqlBin: D:\phpStudy2018\PHPTutorial\MySQL\bin\

signDataSourceBackUpUrl: D:\upload\backup\