charge:
  interfaceUrl: http://localhost:4259/ChargeOnline/interFaceB2C.aspx
 # 一个缩进

spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev
  application:
    name: SignServer
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      enabled: true
  #静态资源映射
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path},file:${signDataSourceBackUpUrl}
#上传文件目录
web:
  upload-path: D:/upload
logging:
  level:
    cn.gljp.sign.admin.mapper : debug




